import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="dark:bg-neutral-800 bg-neutral-100 text-neutral-100 dark:neutral-800 ">
        {children}
      </body>
    </html>
  );
}
