import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 *
 * @param root0
 * @param root0.children
 */
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-background">{children}</body>
    </html>
  );
}
