/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/f88WegjhVsE
 */
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  Card,
} from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import React, { Suspense } from "react";
import { Todo, todos } from "@/database/schema";
import { Input } from "./ui/input";
import { Button } from "./ui/button";
import { addTodo } from "@/app/actions/add-todo";
import { db } from "@/database";
import { LoaderCircle } from "lucide-react";

/**
 * @returns {React.ReactElement} TodoCard
 */
export function TodoCard() {
  return (
    <Card className="mx-auto w-full max-w-sm">
      <CardHeader className="text-center">
        <CardTitle>Today todos</CardTitle>
        <CardDescription>What you need to do today</CardDescription>
      </CardHeader>
      <CardContent className="grid gap-4">
        <Suspense fallback={<LoaderCircle className="animate-spin" />}>
          <TodoList />
        </Suspense>
        <form action={addTodo}>
          <div className="flex items-center gap-4">
            <Input placeholder="Add a new todo" type="text" name="title" />
            <Button>Add Todo</Button>
          </div>
        </form>
      </CardContent>
    </Card>
  );
}

/**
 * @returns {React.ReactElement} TodoList
 */
async function TodoList() {
  /**
   * @type {Todo[]}
   */
  const todoList = await db.select().from(todos);

  return (
    <>
      {todoList.map((todo) => (
        <TodoListItem key={todo.id} {...todo} />
      ))}
    </>
  );
}

/**
 * @param {Todo} todo a todo
 * @returns {React.ReactElement} TodoListItem
 */
function TodoListItem(todo) {
  return (
    <div className="flex items-center gap-4">
      <Checkbox id="email" />
      <Label htmlFor="email">{todo.title}</Label>
    </div>
  );
}
