/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/f88WegjhVsE
 */
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  Card,
} from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import React from "react";
import { Todo } from "@/database/schema";

/**
 *
 */
export function TodoCard() {
  return (
    <Card className="mx-auto w-full max-w-sm">
      <CardHeader className="text-center">
        <CardTitle>Today todos</CardTitle>
        <CardDescription>What you need to do today</CardDescription>
      </CardHeader>
      <CardContent className="grid gap-4">
        <TodoListItem completed={false} title="something" />
        <TodoListItem completed={false} title="something1" />
        <TodoListItem completed={false} title="something2" />
        <TodoListItem completed={false} title="something3" />
        <TodoListItem completed={false} title="something4" />
      </CardContent>
    </Card>
  );
}

/**
 *
 * @param {Todo} todo
 * @returns {React.ReactElement}
 */
function TodoListItem(todo) {
  return (
    <div className="flex items-center gap-4">
      <Checkbox id="email" />
      <Label htmlFor="email">{todo.title}</Label>
    </div>
  );
}
