/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/f88WegjhVsE
 */
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  Card,
} from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

/**
 *
 */
export function TodoCard() {
  return (
    <Card className="mx-auto w-full max-w-sm">
      <CardHeader className="text-center">
        <CardTitle>Today todos</CardTitle>
        <CardDescription>What you need to do today</CardDescription>
      </CardHeader>
      <CardContent className="grid gap-4">
        <div className="flex items-center gap-4">
          <Checkbox defaultChecked id="email" />
          <Label htmlFor="email">Email team about project updates</Label>
        </div>
        <div className="flex items-center gap-4">
          <Checkbox id="meeting" />
          <Label htmlFor="meeting">Prepare for the afternoon meeting</Label>
        </div>
        <div className="flex items-center gap-4">
          <Checkbox id="review" />
          <Label htmlFor="review">Review the new design proposals</Label>
        </div>
        <div className="flex items-center gap-4">
          <Input placeholder="Add a new todo" type="text" />
          <Button>Add Todo</Button>
        </div>
      </CardContent>
    </Card>
  );
}
